services:
  server:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - public-data:/app/public
    restart: always
    command: ["sh", "-c", "npm run build && npm start"]

  nginx:
    depends_on:
      - server
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: auth-kanban
      MONGO_INITDB_ROOT_USERNAME: timkmitdb
      MONGO_INITDB_ROOT_PASSWORD: 65876587
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  public-data:
  mongo-data: